var search={
  "Acerra Sink": "http://fuzzy-sl.squirrel.link/data/cisite_1",
  "Acqua Fidia": "http://fuzzy-sl.squirrel.link/data/cisite_2",
  "Activity Instances Collection": "http://fuzzy-sl.squirrel.link/data/Activity_collection",
  "Agent Instances Collection": "http://fuzzy-sl.squirrel.link/data/Agent_collection",
  "Auel Maar AU3": "http://fuzzy-sl.squirrel.link/data/cisite_201",
  "Auel Maar AU4": "http://fuzzy-sl.squirrel.link/data/cisite_202",
  "Balta Alba (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_57",
  "Batajnica": "http://fuzzy-sl.squirrel.link/data/cisite_104",
  "Bratul Borcea (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_56",
  "Capezzano": "http://fuzzy-sl.squirrel.link/data/cisite_3",
  "Casola": "http://fuzzy-sl.squirrel.link/data/cisite_4",
  "Castelcivita Cave": "http://fuzzy-sl.squirrel.link/data/cisite_5",
  "Copecchia": "http://fuzzy-sl.squirrel.link/data/cisite_6",
  "Crvena Stiljena (Montenegro)": "http://fuzzy-sl.squirrel.link/data/cisite_51",
  "Cuma": "http://fuzzy-sl.squirrel.link/data/cisite_7",
  "Dehner Maar DE3": "http://fuzzy-sl.squirrel.link/data/cisite_203",
  "Dobrogea (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_53",
  "Dunaszekcs\u0151": "http://fuzzy-sl.squirrel.link/data/cisite_103",
  "Entity Instances Collection": "http://fuzzy-sl.squirrel.link/data/Entity_collection",
  "Franchthi Cave (Greece)": "http://fuzzy-sl.squirrel.link/data/cisite_45",
  "Golema Pesht Cave near Zdunje (Macedonia)": "http://fuzzy-sl.squirrel.link/data/cisite_50",
  "Gulf of Naples": "http://fuzzy-sl.squirrel.link/data/cisite_8",
  "Haua-Fteah (Libya)": "http://fuzzy-sl.squirrel.link/data/cisite_65",
  "Kisiljevo (Serbia)": "http://fuzzy-sl.squirrel.link/data/cisite_61",
  "Klissoura (Greece)": "http://fuzzy-sl.squirrel.link/data/cisite_46",
  "Kostenki (Russia)": "http://fuzzy-sl.squirrel.link/data/cisite_60",
  "Kostenki-Borshchevo (Russia)": "http://fuzzy-sl.squirrel.link/data/cisite_59",
  "Kozarnika Cave (Bulgaria)": "http://fuzzy-sl.squirrel.link/data/cisite_42",
  "Lago Grande di Monticchio": "http://fuzzy-sl.squirrel.link/data/cisite_13",
  "Lago Patria (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_9",
  "Lake Ohrid (Albania)": "http://fuzzy-sl.squirrel.link/data/cisite_41",
  "Lake Ohrid (Macedonia)": "http://fuzzy-sl.squirrel.link/data/cisite_49",
  "Lake Prespa": "http://fuzzy-sl.squirrel.link/data/cisite_106",
  "Lower Danube Basin (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_55",
  "Marina di Cassano (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_10",
  "Massaquano (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_11",
  "Monte Echia (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_12",
  "Monticchio (Bagni)": "http://fuzzy-sl.squirrel.link/data/cisite_14",
  "Monticchio Lakes": "http://fuzzy-sl.squirrel.link/data/cisite_15",
  "Murge Plateau": "http://fuzzy-sl.squirrel.link/data/cisite_16",
  "Naples": "http://fuzzy-sl.squirrel.link/data/cisite_17",
  "Orlovat": "http://fuzzy-sl.squirrel.link/data/cisite_101",
  "Pacognano": "http://fuzzy-sl.squirrel.link/data/cisite_18",
  "Paglicci Cave": "http://fuzzy-sl.squirrel.link/data/cisite_19",
  "Pellezzano": "http://fuzzy-sl.squirrel.link/data/cisite_20",
  "Penta": "http://fuzzy-sl.squirrel.link/data/cisite_21",
  "Person": "http://fuzzy-sl.squirrel.link/data/nonns_Person.html",
  "Person Instances Collection": "http://fuzzy-sl.squirrel.link/data/Person_collection",
  "Phlegraean Fields": "http://fuzzy-sl.squirrel.link/data/cisite_22",
  "Place Instances Collection": "http://fuzzy-sl.squirrel.link/data/Place_collection",
  "Point Instances Collection": "http://fuzzy-sl.squirrel.link/data/Point_collection",
  "Ponti Rossi (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_23",
  "Pozzuoli Bay": "http://fuzzy-sl.squirrel.link/data/cisite_24",
  "Pucara": "http://fuzzy-sl.squirrel.link/data/cisite_25",
  "Punta Marmolite": "http://fuzzy-sl.squirrel.link/data/cisite_26",
  "Rasova": "http://fuzzy-sl.squirrel.link/data/cisite_105",
  "Russian Plane": "http://fuzzy-sl.squirrel.link/data/cisite_58",
  "San Marco": "http://fuzzy-sl.squirrel.link/data/cisite_29",
  "San Nicola La Strada": "http://fuzzy-sl.squirrel.link/data/cisite_30",
  "Sant\u2018 Agata dei due Golfi": "http://fuzzy-sl.squirrel.link/data/cisite_27",
  "Sant\u2018 Angelo a Scala": "http://fuzzy-sl.squirrel.link/data/cisite_28",
  "Scarafea Area": "http://fuzzy-sl.squirrel.link/data/cisite_31",
  "Serino": "http://fuzzy-sl.squirrel.link/data/cisite_32",
  "Site Instances Collection": "http://fuzzy-sl.squirrel.link/data/Site_collection",
  "Southern Ukraine": "http://fuzzy-sl.squirrel.link/data/cisite_64",
  "Stala\u0107": "http://fuzzy-sl.squirrel.link/data/cisite_102",
  "Starza": "http://fuzzy-sl.squirrel.link/data/cisite_33",
  "Susak Island (Greece)": "http://fuzzy-sl.squirrel.link/data/cisite_48",
  "Tabula Traiana (Serbia)": "http://fuzzy-sl.squirrel.link/data/cisite_62",
  "Temnata Cave (Bulgaria)": "http://fuzzy-sl.squirrel.link/data/cisite_43",
  "Tenaghi Philippon (Greece)": "http://fuzzy-sl.squirrel.link/data/cisite_47",
  "Titel Pleateau (Serbia)": "http://fuzzy-sl.squirrel.link/data/cisite_63",
  "Toplitsa Cave (Bulgaria)": "http://fuzzy-sl.squirrel.link/data/cisite_44",
  "Torregaveta": "http://fuzzy-sl.squirrel.link/data/cisite_34",
  "Trefola": "http://fuzzy-sl.squirrel.link/data/cisite_35",
  "Tufara": "http://fuzzy-sl.squirrel.link/data/cisite_36",
  "Tufarella Area": "http://fuzzy-sl.squirrel.link/data/cisite_37",
  "Urluia (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_52",
  "Vico Equense": "http://fuzzy-sl.squirrel.link/data/cisite_38",
  "Villa di Briano (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_39",
  "Vlasca (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_54",
  "Voscone Area": "http://fuzzy-sl.squirrel.link/data/cisite_40",
  "fsl:Georeferencing Instances Collection": "http://fuzzy-sl.squirrel.link/data/fsl:Georeferencing_collection"
}